### PR TITLE
ft: Added mark complete

### PR DESCRIPTION
**Pull request by SamuelSabasNayo**
### What does this PR do?
- A signed user to mark completed todos.

### Description of Task to be completed?
- A signed user to mark completed todos.

### How should this be manually tested?
- Anyone can test it using this link **https://samuel-todolist-app.netlify.app**.

### Any background context you want to provide?
- N/A

### What are the relevant Trello stories?
- #4
### Screenshots (if appropriate)
- 
Screen Shot 2020-11-11 at 09 19 06

### Questions
- N/A

### CODE REVIEW

**Comment by thepatrickniyo** [comment]
Good work @SamuelSabasNayo

**Review by Monehin — CHANGES_REQUESTED** [review]
Currently, a user can add an empty item to your todo list. Kindly fix this either by disabling the add button if the text field is empty or notify the user if they try to add an empty item.

**Comment by SamuelSabasNayo** [comment]
> Currently, a user can add an empty item to your todo list. Kindly fix this either by disabling the add button if the text field is empty or notify the user if they try to add an empty item.

Ok, let me work on it.

**Comment by ConstantineMaliza** [comment]
great work samuel

**Pull request merged**
