### PR TITLE
chore: Added authorisation to current user

### PR DESCRIPTION
**Pull request by SamuelSabasNayo**
### What does this PR do?
- Authorise a current user to see his/ her own todos.

### Description of Task to be completed?
- Authorise a current user to see his/ her own todos.

### How should this be manually tested?
- A logged-in user can interact with his/ her todos.

### Any background context you want to provide?
- N/A

### What are the relevant Trello stories?
- #10

### Screenshots (if appropriate)
- 
Screen Shot 2020-11-12 at 13 45 12

### Questions
- N/A

### CODE REVIEW

**Comment by thepatrickniyo** [comment]
Good work @SamuelSabasNayo

**Review by SimonImanigirimpuhwe — APPROVED** [review]
Good job! The PR can be merged.

**Comment by SamuelSabasNayo** [comment]
> Good job! The PR can be merged.

**Comment by SamuelSabasNayo** [comment]
@PatrickNiyogitare28 @SimonImanigirimpuhwe Thanks for the review.

**Pull request merged**
